## Homework - Problem 19

`Input/gradient_data2.csv`를 이용하여 Gradient Boosting을 수행한다.

다음 조건을 사용한다.

- `test_size=0.2`
- `random_state=42`
- `n_estimators=100`
- `learning_rate = 0.01, 0.05, 0.1, 0.2`

다음 질문에 답하시오.

- 각 `learning_rate`의 Test Accuracy를 소수점 셋째 자리까지 적으시오.
- 가장 높은 Test Accuracy를 보인 `learning_rate`를 모두 적으시오.

답만 제출하시오.

In [16]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split

In [11]:
df = pd.read_csv('../Input/gradient_data.csv')
display(df.head())

         x1        x2        x3        x4        x5        x6  y
0 -0.501840  1.033053 -0.637583 -1.435106 -1.504616  0.593028  0
1  1.802857 -1.901652 -1.713152  0.283510 -1.717857 -1.310455  1
2  0.927976 -1.911506 -0.361484 -1.258919  1.637718  1.489578  1
3  0.394634 -0.705559 -0.755130 -0.885428 -1.239485  0.452465  1
4 -1.375925 -0.045427  0.708483 -1.125161  1.285001 -1.371184  0

In [12]:
X = df.drop('y', axis=1)
y = df['y']

display(X.head())
display(y.head())

print(X.shape, y.shape)

         x1        x2        x3        x4        x5        x6
0 -0.501840  1.033053 -0.637583 -1.435106 -1.504616  0.593028
1  1.802857 -1.901652 -1.713152  0.283510 -1.717857 -1.310455
2  0.927976 -1.911506 -0.361484 -1.258919  1.637718  1.489578
3  0.394634 -0.705559 -0.755130 -0.885428 -1.239485  0.452465
4 -1.375925 -0.045427  0.708483 -1.125161  1.285001 -1.371184

0    0
1    1
2    1
3    1
4    0
Name: y, dtype: int64

(1200, 6) (1200,)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape, X_test.shape)

(960, 6) (240, 6)

In [28]:
learning_rates = [0.01, 0.05, 0.1, 0.2]
count = 0

acs = pd.DataFrame(columns=['Learning Rate', 'Number of Estimators', 'Accuracy', 'Score'], index=range(len(learning_rates)))

for i in learning_rates:
    model = GradientBoostingClassifier(
        random_state=42,
        n_estimators=100,
        learning_rate = i
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    accuracy = model.score(X_test, y_pred)

    score = model.score(X_test, y_test)

    acs.loc[count] = [i, 100, accuracy, score]

    count += 1

display(acs)

  Learning Rate Number of Estimators Accuracy     Score
0          0.01                  100      1.0     0.625
1          0.05                  100      1.0  0.641667
2           0.1                  100      1.0  0.654167
3           0.2                  100      1.0    0.7625