## Homework - Problem 19

`Input/gradient_data2.csv`를 이용하여 Gradient Boosting을 수행한다.

다음 조건을 사용한다.

- `test_size=0.2`
- `random_state=42`
- `n_estimators=100`
- `learning_rate = 0.01, 0.05, 0.1, 0.2`

다음 질문에 답하시오.

- 각 `learning_rate`의 Test Accuracy를 소수점 셋째 자리까지 적으시오.
- 가장 높은 Test Accuracy를 보인 `learning_rate`를 모두 적으시오.

답만 제출하시오.

In [17]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [18]:
df = pd.read_csv('../Input/gradient_data2.csv')
display(df.head())

         x1        x2        x3        x4        x5        x6  y
0  0.173620 -1.827490 -1.117732 -0.351969 -1.187867  0.119280  1
1 -0.886522  1.707396 -0.675594  1.946000 -1.086080  1.256365  0
2 -0.301930 -0.281293 -0.718493  0.281366  0.327228 -0.648679  0
3  1.379105  0.523944 -0.401529 -1.163328  0.616817 -0.235118  0
4 -1.981125 -1.617105 -0.530547 -1.768432  1.729772  0.163962  1

In [19]:
X = df.drop('y', axis=1)
y = df['y']

display(X.head())
display(y.head())

print(X.shape, y.shape)

         x1        x2        x3        x4        x5        x6
0  0.173620 -1.827490 -1.117732 -0.351969 -1.187867  0.119280
1 -0.886522  1.707396 -0.675594  1.946000 -1.086080  1.256365
2 -0.301930 -0.281293 -0.718493  0.281366  0.327228 -0.648679
3  1.379105  0.523944 -0.401529 -1.163328  0.616817 -0.235118
4 -1.981125 -1.617105 -0.530547 -1.768432  1.729772  0.163962

0    1
1    0
2    0
3    0
4    1
Name: y, dtype: int64

(1200, 6) (1200,)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(X_train.shape, X_test.shape)

(960, 6) (240, 6)

In [21]:
learning_rates = [0.01, 0.05, 0.1, 0.2]
count = 0

acs = pd.DataFrame(columns=['Learning Rate', 'n_estimators', 'Score'], index=range(len(learning_rates)))

for i in learning_rates:
    model = GradientBoostingClassifier(
        random_state=42,
        n_estimators=100,
        learning_rate = i
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    score = model.score(X_test, y_test)

    acs.loc[count] = [i, 100, f"{score:0.3f}"]

    count += 1

display(acs)

  Learning Rate n_estimators  Score
0          0.01          100  0.617
1          0.05          100  0.725
2           0.1          100  0.762
3           0.2          100  0.762