# 03_Numpy, Pandas

Machine Learning에서는 Data를 이용하여 Model을 학습한다.

앞 강의에서는 Machine Learning Problem을 다음과 같이 표현하였다.

$$
X \rightarrow y
$$

그렇다면 실제 Data를 Python에서는 어떻게 다룰 수 있을까?

이번 강의에서는 Machine Learning에서 Data를 다루기 위해 많이 사용하는 두 가지 Python Library를 배운다.

- NumPy
- Pandas

그리고 CSV File을 읽어 실제 Machine Learning에 사용할 $X$와 $y$를 만드는 과정을 살펴본다.

이번 강의의 전체 과정은 다음과 같다.

> CSV → DataFrame → Explore → Select → Transform → $X$, $y$

## NumPy

NumPy는 Numerical Data를 효율적으로 처리하기 위한 Python Library이다.

NumPy에서 가장 기본적인 Data Structure는 ndarray이다.

Python의 List와 비슷하게 여러 값을 저장할 수 있지만, Numerical Calculation을 효율적으로 수행할 수 있다.

일반적으로 NumPy를 다음과 같이 불러온다.

In [1]:
import numpy as np

data = [10, 20, 30, 40, 50]

x = np.array(data)

print(x)
print(type(x))

[10 20 30 40 50]
<class 'numpy.ndarray'>

In [2]:
print(data)
print(type(data))

[10, 20, 30, 40, 50]
<class 'list'>

NumPy Array의 중요한 특징 중 하나는 Array 전체에 Mathematical Operation을 쉽게 적용할 수 있다는 것이다.

예를 들어 모든 값에 2를 곱하려고 한다.

In [3]:
print(x * 2)

[ 20  40  60  80 100]

In [4]:
print(data * 2)

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

Python List에 `* 2`를 적용하는 것과 NumPy Array에 `* 2`를 적용하는 것은 의미가 다르다.

NumPy에서는 각 Element에 Mathematical Operation이 적용된다.

Machine Learning에서는 많은 Numerical Data에 동일한 계산을 수행해야 하므로 이러한 기능이 매우 유용하다.

## Two-Dimensional Array

Machine Learning Data는 하나의 값만 가지는 경우보다 여러 Feature를 가지는 경우가 많다.

예를 들어 학생 한 명에 대해 다음 세 가지 Feature를 사용한다고 하자.

- Study Hours
- Attendance
- Assignment Score

네 명의 학생에 대한 Input Data $X$는 다음과 같이 표현할 수 있다.

$$
X=
\begin{bmatrix}
5 & 70 & 65 \\
8 & 80 & 72 \\
12 & 90 & 85 \\
15 & 95 & 92
\end{bmatrix}
$$

이를 NumPy의 Two-Dimensional Array로 만들 수 있다.

In [5]:
X = np.array([
    [5, 70, 65],
    [8, 80, 72],
    [12, 90, 85],
    [15, 95, 92]
])

print(X)
print(X.shape)

[[ 5 70 65]
 [ 8 80 72]
 [12 90 85]
 [15 95 92]]
(4, 3)

## Selecting Data

NumPy Array에서는 필요한 Sample이나 Feature를 선택할 수 있다.

Machine Learning에서는 전체 Dataset을 항상 그대로 사용하는 것이 아니라 필요한 Row와 Column을 선택해야 하는 경우가 많다.

Python의 Index는 0부터 시작한다.

In [7]:
# 첫 번째 Sample 선택
print(X[0])

# 모든 Sample의 첫 번째 Feature 선택
study_hours = X[:, 0]
print(study_hours)

# 첫 번째와 두 번째 Feature 선택
features = X[:, 0:2]    # slicing   a:b  a<=x<b
print(features)

[ 5 70 65]
[ 5  8 12 15]
[[ 5 70]
 [ 8 80]
 [12 90]
 [15 95]]

## From NumPy to Pandas

NumPy는 Numerical Calculation에 매우 유용하다.

그러나 실제 Dataset에서는 각 Column이 무엇을 의미하는지 아는 것이 중요하다.

예를 들어 다음과 같은 Data를 생각해 보자.

- Country
- Year
- Population
- Income
- Life Expectancy

이처럼 Row와 Column으로 구성되고 각 Column이 의미를 가지는 Data를 다룰 때는 Pandas의 DataFrame이 편리하다.

In [8]:
import pandas as pd

# Dictionary를 이용하여 DataFrame 생성
data = {
    "StudyHours": [5, 8, 12, 15],
    "Attendance": [70, 80, 90, 95],
    "Assignment": [65, 72, 85, 92],
    "FinalScore": [62, 70, 84, 91]
}

df = pd.DataFrame(data)

# DataFrame 확인
df

   StudyHours  Attendance  Assignment  FinalScore
0           5          70          65          62
1           8          80          72          70
2          12          90          85          84
3          15          95          92          91

## Using Data from Google Drive

Google Colab에서 Google Drive에 저장된 Data File을 사용할 수 있다.

먼저 Google Drive를 Colab에 Mount한다.

Mount가 완료되면 Google Drive의 File을 일반적인 File처럼 Python에서 사용할 수 있다.

이번 강의에서는 Google Drive에 저장된 CSV File을 Pandas DataFrame으로 읽어 사용한다.

> Google Drive → Mount → CSV → DataFrame

In [9]:
from google.colab import drive

# Google Drive를 Colab에 Mount
drive.mount('/content/drive')

# 강의용 Data가 저장된 Folder
data_path = "/content/drive/My Drive/Colab Notebooks/0_ML/Input/"

Mounted at /content/drive

## Reading and Exploring CSV Data

실제 Machine Learning Data는 CSV File로 제공되는 경우가 많다.

Pandas의 `read_csv()`를 이용하면 CSV File을 DataFrame으로 읽을 수 있다.

CSV File을 읽은 후에는 바로 Machine Learning을 적용하기보다 먼저 Data의 구조와 내용을 확인해야 한다.

주로 다음을 확인한다.

- Data의 일부
- Row와 Column의 수
- Column Name
- Data Type

In [10]:
# CSV File을 DataFrame으로 읽기
df = pd.read_csv(data_path+"life_expectancy.csv")

# 처음 5개의 Sample 확인
display(df.head())

# Data의 크기 확인
print("Shape:", df.shape)

# Column Name 확인
print("Columns:", df.columns.tolist())

# 각 Column의 Data Type 확인
print("\nData Types:")
print(df.dtypes)

,Country,Year,Status,Life expectancy,Adult mortality,Infant deaths,Alcohol,Percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,Thinness 1-19 years,Thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

Shape: (2938, 22)
Columns: ['Country', 'Year', 'Status', 'Life expectancy', 'Adult mortality', 'Infant deaths', 'Alcohol', 'Percentage expenditure', 'Hepatitis B', 'Measles', 'BMI', 'Under-five deaths ', 'Polio', 'Total expenditure', 'Diphtheria ', 'HIV/AIDS', 'GDP', 'Population', 'Thinness 1-19 years', 'Thinness 5-9 years', 'Income composition of resources', 'Schooling']

Data Types:
Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult mortality                    float64
Infant deaths                        int64
Alcohol                            float64
Percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
BMI                                float64
Under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
HIV/AIDS                           float64
GDP                                float64
Population                         float64
Thinness 1-19 years                float64
Thinness 5-9 years                 float64
Income composition of resources    float64
Schooling                          float64
dtype: object

## Selecting Data

DataFrame에서 Column Name을 이용하여 필요한 Variable을 선택할 수 있다.

하나의 Column을 선택할 수도 있고 여러 Column을 동시에 선택할 수도 있다.

또한 조건을 이용하여 특정 Sample만 선택할 수 있다.

어떤 Data를 선택할 것인지는 해결하고자 하는 Problem에 따라 결정한다.

In [12]:
# 하나의 Column 선택
life = df["Life expectancy"]
print(life.head())

# 여러 Column 선택
selected = df[["Income composition of resources", "Population", "Life expectancy"]]
display(selected.head())

# 특정 조건을 만족하는 Sample 선택
high_income = df[df["Income composition of resources"] > 0.5]
display(high_income.head())

0    65.0
1    59.9
2    59.9
3    59.5
4    59.2
Name: Life expectancy, dtype: float64

   Income composition of resources  Population  Life expectancy
0                            0.479  33736494.0             65.0
1                            0.476    327582.0             59.9
2                            0.470  31731688.0             59.9
3                            0.463   3696958.0             59.5
4                            0.454   2978599.0             59.2

,Country,Year,Status,Life expectancy,Adult mortality,Infant deaths,Alcohol,Percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,Thinness 1-19 years,Thinness 5-9 years,Income composition of resources,Schooling
16,Albania,2015,Developing,77.8,74.0,0,4.60,364.975229,99.0,0,...,99.0,6.00,99.0,0.1,3954.227830,28873.0,1.2,1.3,0.762,14.2
17,Albania,2014,Developing,77.5,8.0,0,4.51,428.749067,98.0,0,...,98.0,5.88,98.0,0.1,4575.763787,288914.0,1.2,1.3,0.761,14.2
18,Albania,2013,Developing,77.2,84.0,0,4.76,430.876979,99.0,0,...,99.0,5.66,99.0,0.1,4414.723140,289592.0,1.3,1.4,0.759,14.2
19,Albania,2012,Developing,76.9,86.0,0,5.14,412.443356,99.0,9,...,99.0,5.59,99.0,0.1,4247.614380,2941.0,1.3,1.4,0.752,14.2
20,Albania,2011,Developing,76.6,88.0,0,5.37,437.062100,99.0,28,...,99.0,5.71,99.0,0.1,4437.178680,295195.0,1.4,1.5,0.738,13.3

## Transforming Data

기존 Variable을 그대로 사용하는 것뿐 아니라 Problem에 맞게 새로운 Variable을 만들 수도 있다.

이러한 과정을 Data Transformation이라고 한다.

예를 들어 단위를 변경하거나 기존 Variable을 이용하여 새로운 Feature를 만들 수 있다.

In [ ]:
# Income의 단위를 1000 단위로 변환하여 새로운 Column 생성
df["Income1000"] = df["Income composition of resources"] / 1000

# 변환 결과 확인
display(df.head())

,Country,Year,Status,Life expectancy,Adult mortality,Infant deaths,Alcohol,Percentage expenditure,Hepatitis B,Measles,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,Thinness 1-19 years,Thinness 5-9 years,Income composition of resources,Schooling,Income1000
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,0.000479
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,0.000476
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,0.000470
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,0.000463
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,0.000454

## From DataFrame to $X$ and $y$

Machine Learning Problem을 다음과 같이 정의했다고 하자.

> 국가의 여러 정보를 이용하여 Life Expectancy를 예측하고 싶다.

이 Problem에서 예측에 사용할 Variable을 $X$, 예측하고자 하는 Variable을 $y$로 선택한다.

$$
X \rightarrow y
$$

중요한 것은 DataFrame 전체가 자동으로 $X$가 되는 것이 아니라는 점이다.

$X$와 $y$는 해결하려는 Problem에 따라 우리가 결정한다.

In [13]:
# Input X 선택
X = df[["Income composition of resources", "Population", "Schooling"]]

# Output y 선택
y = df["Life expectancy"]

# 선택한 X와 y 확인
display(X.head())
display(y.head())

# Shape 확인
print("X shape:", X.shape)
print("y shape:", y.shape)

   Income composition of resources  Population  Schooling
0                            0.479  33736494.0       10.1
1                            0.476    327582.0       10.0
2                            0.470  31731688.0        9.9
3                            0.463   3696958.0        9.8
4                            0.454   2978599.0        9.5

0    65.0
1    59.9
2    59.9
3    59.5
4    59.2
Name: Life expectancy, dtype: float64

X shape: (2938, 3)
y shape: (2938,)

### HW_03

`Input` 디렉토리의 `california_housing.csv`를 Pandas DataFrame으로 읽고 다음 질문에 답하시오.

- DataFrame의 Row 수와 Column 수를 적으시오.
- `MedHouseVal`의 평균을 적으시오.
- `MedInc`가 5 이상인 Row의 수를 적으시오.
- `MedInc`, `HouseAge`, `AveRooms`를 선택하여 DataFrame `X`를 만들고 `X`의 Shape를 적으시오.

각 문제의 실행 결과를 제출하시오.